<?php

declare(strict_types=1);

namespace App\Http\Controllers;

use App\Models\NewStudent;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\View\View;

class RegisterStudentController extends Controller
{
    public function form(string $token): View
    {
        // Permanent token - always show form
        if ($token === \App\Http\Controllers\Admin\NewStudentController::PERMANENT_TOKEN) {
            return view('register-student.form');
        }

        // Legacy token-based links - still work for backward compatibility
        $newStudent = NewStudent::where('token', $token)->firstOrFail();

        if ($newStudent->converted) {
            return view('register-student.closed');
        }

        return view('register-student.form', compact('newStudent'));
    }

    public function submit(Request $request, string $token): RedirectResponse
    {
        // Validate token
        if ($token !== \App\Http\Controllers\Admin\NewStudentController::PERMANENT_TOKEN) {
            $newStudent = NewStudent::where('token', $token)->firstOrFail();
            if ($newStudent->converted) {
                return back()->with('status', 'Form ini sudah tidak aktif.');
            }
        }

        $validated = $request->validate([
            'parent_name' => ['required', 'string', 'max:255'],
            'whatsapp' => ['required', 'string', 'max:20'],
            'address' => ['nullable', 'string', 'max:500'],
            'students' => ['required', 'array', 'min:1'],
            'students.*.name' => ['required', 'string', 'max:255'],
            'notes' => ['nullable', 'string'],
        ]);

        // Save to database (token auto-generated by model)
        NewStudent::create([
            'name' => $validated['parent_name'],
            'parent_name' => $validated['parent_name'],
            'whatsapp' => $validated['whatsapp'],
            'address' => $validated['address'] ?? null,
            'students_data' => $validated['students'],
            'notes' => $validated['notes'] ?? null,
        ]);

        return redirect()
            ->route('register-student.success')
            ->with('status', 'Data berhasil dikirim.');
    }

    public function success(): View
    {
        return view('register-student.success');
    }
}