<?php

declare(strict_types=1);

namespace App\Http\Controllers;

use App\Models\NewStudent;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\View\View;

class RegisterStudentController extends Controller
{
    public function form(string $token): View
    {
        // Permanent token - always show form
        if ($token === \App\Http\Controllers\Admin\NewStudentController::PERMANENT_TOKEN) {
            return view('register-student.form');
        }

        // Legacy token-based links - still work for backward compatibility
        $newStudent = NewStudent::where('token', $token)->firstOrFail();

        if ($newStudent->converted) {
            return view('register-student.closed');
        }

        return view('register-student.form', compact('newStudent'));
    }

    public function submit(Request $request, string $token): RedirectResponse
    {
        // Validate token
        if ($token !== \App\Http\Controllers\Admin\NewStudentController::PERMANENT_TOKEN) {
            $newStudent = NewStudent::where('token', $token)->firstOrFail();
            if ($newStudent->converted) {
                return back()->with('status', 'Form ini sudah tidak aktif.');
            }
        }

        $validated = $request->validate([
            'parent_name' => ['required', 'string', 'max:255'],
            'whatsapp' => ['required', 'string', 'max:20', 'regex:/^08[0-9]{8,12}$/'],
            'address' => ['nullable', 'string', 'max:500'],
            'students' => ['required', 'array', 'min:1'],
            'students.*.nickname' => ['required', 'string', 'max:255'],
            'students.*.full_name' => ['nullable', 'string', 'max:255'],
            'notes' => ['nullable', 'string'],
        ]);

        // Reject duplicate submissions: block if the same parent phone + student nickname
        // already has an unconverted registration pending.
        $phone = $this->cleanPhone($validated['whatsapp']);
        foreach ($validated['students'] as $studentData) {
            $nickname = trim((string) ($studentData['nickname'] ?? ''));
            if ($nickname === '') continue;

            $duplicate = NewStudent::where('converted', false)
                ->where('whatsapp', $phone)
                ->get()
                ->first(function ($record) use ($nickname) {
                    $studentsData = $record->students_data ?? [];
                    foreach ($studentsData as $s) {
                        $existingNickname = trim((string) ($s['nickname'] ?? $s['name'] ?? ''));
                        if ($existingNickname !== '' && strcasecmp($existingNickname, $nickname) === 0) {
                            return true;
                        }
                    }
                    return false;
                });

            if ($duplicate) {
                return back()
                    ->with('status', "Murid \"{$nickname}\" sudah terdaftar dan belum dikonversi. Hubungi admin untuk melanjutkan.")
                    ->withInput();
            }
        }

        // Save to database (token auto-generated by model)
        NewStudent::create([
            'name' => $validated['parent_name'],
            'parent_name' => $validated['parent_name'],
            'whatsapp' => $this->cleanPhone($validated['whatsapp']),
            'address' => $validated['address'] ?? null,
            'students_data' => $validated['students'],
            'notes' => $validated['notes'] ?? null,
        ]);

        return redirect()
            ->route('register-student.success')
            ->with('status', 'Data berhasil dikirim.');
    }

    public function success(): View
    {
        return view('register-student.success');
    }

    private function cleanPhone(string $phone): string
    {
        $phone = preg_replace('/[^0-9]/', '', $phone);

        // Keep as 08XXXXXXXXX format in database
        if (strlen($phone) > 13) {
            $phone = substr($phone, -13);
        }

        // Ensure starts with 08
        if (str_starts_with($phone, '62')) {
            $phone = '0' . substr($phone, 2);
        } elseif (! str_starts_with($phone, '0')) {
            $phone = '0' . $phone;
        }

        return $phone;
    }
}
